#!/usr/bin/env bash



absolute_path() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

resolve_symlink() (
    if [[ $OSTYPE != darwin* ]]; then minusFarg="-f"; fi
    sym_resolved=$(readlink ${minusFarg} $1)

    if [[ -n $sym_resolved ]]; then
        echo $sym_resolved
    else
        echo $1
    fi
)


abs_kscript_path=$(resolve_symlink $(absolute_path $0))

## resolve application jar path from script location and convert to windows path when using cygwin
jarPath=$(dirname $abs_kscript_path)/kscript.jar

if [[ $(uname) == CYGWIN* ]]; then
    jarPath=$(cygpath -w ${jarPath})
    [[ ! -z $KOTLIN_HOME ]] && KOTLIN_HOME=$(cygpath -w ${KOTLIN_HOME})
fi

## -J -D (borrowed from 'kotlinc')

[ -n "$JAVA_OPTS" ] || JAVA_OPTS="-Xmx256M -Xms32M"

declare -a java_args
declare -a kscript_args

export KSCRIPT_FILE=

while [ $# -gt 0 ]; do
    java_arg=
    case "$1" in
	-D*)
            [[ -z $KSCRIPT_FILE ]] && java_arg="$1"
            ;;
	-J*)
            [[ -z $KSCRIPT_FILE ]] && java_arg="${1:2}"
            ;;
	*)
            if [[ ! $1 =~ ^-. ]]; then
		export KSCRIPT_FILE=$1
	    fi
            ;;
    esac
    if [[ -n $java_arg ]]; then
       java_args=("${java_args[@]}" "$java_arg")
    else
	kscript_args=("${kscript_args[@]}" "$1")
    fi
    shift
done

## KotlinOpts 

if [[ -r $KSCRIPT_FILE ]]; then
    commentOpts=(`grep '^//KOTLIN_OPTS ' $KSCRIPT_FILE | sed 's/^\/\/KOTLIN_OPTS \(.*\)/\1/'`)
    fileOpts=(`grep '^@file:KotlinOpts(' $KSCRIPT_FILE | sed 's/.*"\(.*\)".*/\1/'`)
    if [[ -n $fileOpts || -n $commentOpts ]]; then
	for arg in ${commentOpts[@]} ${fileOpts[@]}; do
	    java_arg=$arg
	    if [[ $arg == -J* ]]; then
		java_arg="${arg:2}"
	    fi
	    java_args=("${java_args[@]}" "$java_arg")
	done
    fi
fi

if [ -z "$JAVACMD" -a -n "$JAVA_HOME" -a -x "$JAVA_HOME/bin/java" ]; then
    JAVACMD="$JAVA_HOME/bin/java"
fi

## run it
exec ${JAVACMD:=java} $JAVA_OPTS "${java_args[@]}" -jar ${jarPath} "${kscript_args[@]}"
